export const productsData = [
  {
    id: "1",
    brand: "TREK",
    name: "Trek Emonda ALR 5 Road Bike",
    image: "/images/trek-emonda-alr-5-road-bike.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    priceBefore: null,
    price: 1319.0,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    colors: ["#2c2c2c"],
    sizes: ["xs", "s", "m", "l"],
  },
  {
    id: "2",
    brand: "PINNACLE",
    name: "Laterite 1 Road Bike",
    image: "/images/pinnacle-laterite-1-road-bike.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    priceBefore: 750.0,
    price: 400.0,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    colors: ["#2c2c2c"],
    sizes: ["xs", "s", "m", "l"],
  },
  {
    id: "3",
    brand: "CANNONDALE",
    name: "CAAD13 Disc Ultegra 2023 Road Bike",
    image: "/images/cannondale-caad-13-disc-ultegra-2023-road-bike.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    priceBefore: 3000.0,
    price: 2099.0,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    colors: ["#2c2c2c"],
    sizes: ["xs", "s", "m", "l"],
  },
  {
    id: "4",
    brand: "SPECIALIZED",
    name: "Roubaix Expert Road Bike",
    image: "/images/roubaix-expert-road-bike.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    priceBefore: 7250.0,
    price: 3649.0,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    colors: ["#0d4663"],
    sizes: ["xs", "s", "m", "l"],
  },
  {
    id: "5",
    brand: "TREK",
    name: "Domane AL 4 Disc Road Bike",
    image: "/images/domane-al-4-disc-road-bike.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    priceBefore: 1625.0,
    price: 1499.0,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    colors: ["#f9f9f7"],
    sizes: ["xs", "s", "m", "l"],
  },
  {
    id: "6",
    brand: "CUBE",
    name: "Axial WS GTC Pro 2022 Women's Road Bike",
    image: "/images/axial-ws-gtc-pro-2022-womens-road-bike.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    priceBefore: 2049.0,
    price: 1499.0,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    colors: ["#2c2c2c"],
    sizes: ["xs", "s"],
  },
  {
    id: "7",
    brand: "TREK",
    name: "Madone SL 6 2024 Road Bike",
    image: "/images/madone-sl-6-2024-road-bike.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    priceBefore: null,
    price: 5625.0,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    colors: ["#700107"],
    sizes: ["xs", "s", "l"],
  },
  {
    id: "8",
    brand: "TREK",
    name: "Emonda SL5 Disc Road Bike",
    image: "/images/emonda-sl5-disc-road-bike.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    priceBefore: null,
    price: 2500.0,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    colors: ["#090d93"],
    sizes: ["s", "l"],
  },
  {
    id: "8",
    brand: "CUBE",
    name: "Cross Race 2023 Cyclocross Bike",
    image: "/images/cross-race-2023-cyclocross-bike.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    priceBefore: 1299.0,
    price: 1039.0,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    colors: ["#0593be"],
    sizes: ["s", "l"],
  },
  {
    id: "9",
    brand: "TREK",
    name: "Domane AL 2 Disc Road Bike",
    image: "/images/domane-al-2-disc-road-bike.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    priceBefore: 1299.0,
    price: 1039.0,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    colors: ["#2c2c2c"],
    sizes: ["s", "l"],
  },
  {
    id: "10",
    brand: "SPECIALIZED",
    name: "Allez E5 Road Bike",
    image: "/images/allez-e5-road-bike.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    priceBefore: 1299.0,
    price: 1039.0,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    colors: ["#8f8b88"],
    sizes: ["s", "l"],
  },
];
